<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Auth.Application\Auth.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlock.Infrastructure\BuildingBlock.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlock.Grpc\BuildingBlock.Grpc.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlock.Contract\BuildingBlock.Contract.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlock.Messaging\BuildingBlock.Messaging.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlock.Messaging.Kafka\BuildingBlock.Messaging.Kafka.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>NovaCore.Auth.Infrastructure</RootNamespace>
    <AssemblyName>NovaCore.Auth.Infrastructure</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
