<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NovaCore.Chat.Infrastructure</RootNamespace>
    <AssemblyName>NovaCore.Chat.Infrastructure</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Chat.Application/Chat.Application.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/BuildingBlock.Infrastructure/BuildingBlock.Infrastructure.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/BuildingBlock.SharedKernel/BuildingBlock.SharedKernel.csproj" />
  </ItemGroup>

</Project>
