<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NovaCore.Order.IntegrationTests</RootNamespace>
    <AssemblyName>NovaCore.Order.IntegrationTests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Services/Order/Order.Application/Order.Application.csproj" />
    <ProjectReference Include="../../../src/Services/Order/Order.Persistence/Order.Persistence.csproj" />
    <ProjectReference Include="../../unit/Common/NovaCore.TestKit/NovaCore.TestKit.csproj" />
  </ItemGroup>

</Project>
