namespace NovaCore.Notification.Domain.Entities;

/// <summary>
/// One Notification Center entry for a specific user. Has nothing to do with Email/Telegram/any
/// delivery channel - purely the "Business Notification" side (see NotificationDispatch for the
/// "Delivery" side). CampaignId is optional - set when this entry was generated by a
/// <see cref="NotificationCampaign"/> execution rather than a <see cref="NotificationRule"/> or a
/// direct call.
/// </summary>
public sealed class UserNotification : AggregateRoot<Guid>, IAuditable, ITenantEntity
{
    public Guid UserId { get; private set; }
    public NotificationCategory Category { get; private set; } = null!;
    public NotificationType Type { get; private set; } = null!;
    public NotificationContent Content { get; private set; } = null!;
    public string? MetadataJson { get; private set; }
    public NotificationPriority Priority { get; private set; }
    public NotificationStatus Status { get; private set; }
    public DateTime? ReadAt { get; private set; }
    public DateTime? ExpiredAt { get; private set; }
    public Guid? CampaignId { get; private set; }

    public Guid TenantId { get; private set; }

    public void AssignTenant(Guid tenantId)
    {
        if (TenantId == Guid.Empty)
            TenantId = tenantId;
    }

    private UserNotification() { }

    public static UserNotification Create(
        Guid id,
        Guid userId,
        NotificationCategory category,
        NotificationType type,
        NotificationContent content,
        NotificationPriority priority = NotificationPriority.Normal,
        string? metadataJson = null,
        DateTime? expiredAt = null,
        Guid? campaignId = null)
    {
        return new UserNotification
        {
            Id = id,
            UserId = userId,
            Category = category,
            Type = type,
            Content = content,
            Priority = priority,
            Status = NotificationStatus.Unread,
            MetadataJson = metadataJson,
            ExpiredAt = expiredAt,
            CampaignId = campaignId,
        };
    }

    public void MarkAsRead()
    {
        if (Status == NotificationStatus.Archived)
            throw ExceptionFactory.InvalidStatus("Cannot mark an archived notification as read.");

        if (Status == NotificationStatus.Read)
            return;

        Status = NotificationStatus.Read;
        ReadAt = DateTime.UtcNow;
    }

    public void Archive()
    {
        if (Status == NotificationStatus.Archived)
            return;

        Status = NotificationStatus.Archived;
    }

    public bool IsExpired(DateTime asOfUtc) => ExpiredAt is not null && asOfUtc >= ExpiredAt.Value;
}
