<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NovaCore.BuildingBlock.Persistence</RootNamespace>
    <AssemblyName>NovaCore.BuildingBlock.Persistence</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlock.Application\BuildingBlock.Application.csproj" />
  </ItemGroup>

</Project>
