<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NovaCore.Auth.Infrastructure.Tests</RootNamespace>
    <AssemblyName>NovaCore.Auth.Infrastructure.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Services/Auth/Auth.Infrastructure/Auth.Infrastructure.csproj" />
  </ItemGroup>

</Project>
