<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlock.Contract\BuildingBlock.Contract.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.HealthCheck" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>NovaCore.BuildingBlock.Grpc</RootNamespace>
    <AssemblyName>NovaCore.BuildingBlock.Grpc</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
