<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NovaCore.Content.Application.Tests</RootNamespace>
    <AssemblyName>NovaCore.Content.Application.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Services/Content/Content.Application/Content.Application.csproj" />
    <ProjectReference Include="../Common/NovaCore.TestKit/NovaCore.TestKit.csproj" />
  </ItemGroup>

</Project>
