<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NovaCore.Auth.Domain.Tests</RootNamespace>
    <AssemblyName>NovaCore.Auth.Domain.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Services/Auth/Auth.Domain/Auth.Domain.csproj" />
    <ProjectReference Include="../Common/NovaCore.TestKit/NovaCore.TestKit.csproj" />
  </ItemGroup>

</Project>
