// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaCore.Content.Persistence.Engine;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NovaCore.Content.Persistence.Storage.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    partial class ContentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NovaCore.BuildingBlock.Persistence.Ef.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consumer_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headers_json");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_retry_at");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("idx_inbox_processed_at");

                    b.HasIndex("MessageId", "ConsumerName")
                        .IsUnique()
                        .HasDatabaseName("idx_inbox_message_consumer_unique");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_inbox_status_created_at");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("idx_inbox_status_next_retry_at");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("NovaCore.BuildingBlock.Persistence.Ef.Inbox.InboxRetryHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consumer_name");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Exception")
                        .HasColumnType("text")
                        .HasColumnName("exception");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Operator")
                        .HasColumnType("text")
                        .HasColumnName("operator");

                    b.Property<int>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result");

                    b.Property<int>("RetryNumber")
                        .HasColumnType("integer")
                        .HasColumnName("retry_number");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_inbox_retry_histories");

                    b.ToTable("inbox_retry_histories", (string)null);
                });

            modelBuilder.Entity("NovaCore.BuildingBlock.Persistence.Ef.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("system")
                        .HasColumnName("actor_type");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_outbox_unprocessed_created_at")
                        .HasFilter("\"processed_at\" IS NULL");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("idx_outbox_processed_at");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.ContentTypes.ContentFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("default_value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<byte>("FieldType")
                        .HasColumnType("smallint")
                        .HasColumnName("field_type");

                    b.Property<bool>("IsLocalized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_localized");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSearchable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_searchable");

                    b.Property<bool>("IsSortable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_sortable");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ValidationConfiguration")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_configuration");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_content_field_definitions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_content_field_definitions_tenant_id");

                    b.HasIndex("ContentTypeId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_content_field_definitions_content_type_id_key");

                    b.ToTable("content_field_definitions", (string)null);
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.ContentTypes.ContentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("schema_version");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_content_types");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_content_types_key");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_content_types_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_content_types_tenant_id");

                    b.ToTable("content_types", (string)null);
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid>("ContentTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_version_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<byte>("Visibility")
                        .HasColumnType("smallint")
                        .HasColumnName("visibility");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_contents");

                    b.HasIndex("ContentTypeId")
                        .HasDatabaseName("ix_contents_content_type_id");

                    b.HasIndex("CurrentVersionId")
                        .HasDatabaseName("ix_contents_current_version_id");

                    b.HasIndex("PublishedVersionId")
                        .HasDatabaseName("ix_contents_published_version_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_contents_slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_contents_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contents_tenant_id");

                    b.HasIndex("Visibility")
                        .HasDatabaseName("ix_contents_visibility");

                    b.ToTable("contents", (string)null);
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.ContentAudience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AudienceReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("audience_reference_id");

                    b.Property<byte>("AudienceType")
                        .HasColumnType("smallint")
                        .HasColumnName("audience_type");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_content_audiences");

                    b.HasIndex("ContentId")
                        .HasDatabaseName("ix_content_audiences_content_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_content_audiences_tenant_id");

                    b.ToTable("content_audiences", (string)null);
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.ContentContributor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<byte>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_content_contributors");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_content_contributors_tenant_id");

                    b.HasIndex("ContentId", "UserId")
                        .HasDatabaseName("ix_content_contributors_content_id_user_id");

                    b.ToTable("content_contributors", (string)null);
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.ContentLocalization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("culture");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_content_localizations");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_content_localizations_tenant_id");

                    b.HasIndex("VersionId")
                        .HasDatabaseName("ix_content_localizations_version_id");

                    b.HasIndex("ContentId", "Culture")
                        .IsUnique()
                        .HasDatabaseName("ix_content_localizations_content_id_culture");

                    b.ToTable("content_localizations", (string)null);
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.ContentPublication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UnpublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unpublished_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_content_publications");

                    b.HasIndex("ContentId")
                        .HasDatabaseName("ix_content_publications_content_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_content_publications_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_content_publications_tenant_id");

                    b.HasIndex("VersionId")
                        .HasDatabaseName("ix_content_publications_version_id");

                    b.ToTable("content_publications", (string)null);
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.ContentRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<byte>("RelationshipType")
                        .HasColumnType("smallint")
                        .HasColumnName("relationship_type");

                    b.Property<Guid>("SourceContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_content_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_content_relationships");

                    b.HasIndex("SourceContentId")
                        .HasDatabaseName("ix_content_relationships_source_content_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_content_relationships_tenant_id");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_content_relationships_target_type_target_id");

                    b.ToTable("content_relationships", (string)null);
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.ContentTaxonomyAssignment", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_id");

                    b.Property<Guid>("TaxonomyId")
                        .HasColumnType("uuid")
                        .HasColumnName("taxonomy_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ContentId", "TaxonomyId")
                        .HasName("pk_content_taxonomy_assignments");

                    b.HasIndex("TaxonomyId")
                        .HasDatabaseName("ix_content_taxonomy_assignments_taxonomy_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_content_taxonomy_assignments_tenant_id");

                    b.ToTable("content_taxonomy_assignments", (string)null);
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.ContentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_content_versions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_content_versions_tenant_id");

                    b.HasIndex("ContentId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_content_versions_content_id_version_number");

                    b.ToTable("content_versions", (string)null);
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.ContentWorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("current_state");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("StartedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("started_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_content_workflow_instances");

                    b.HasIndex("ContentId")
                        .HasDatabaseName("ix_content_workflow_instances_content_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_content_workflow_instances_tenant_id");

                    b.HasIndex("WorkflowDefinitionId")
                        .HasDatabaseName("ix_content_workflow_instances_workflow_definition_id");

                    b.ToTable("content_workflow_instances", (string)null);
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Taxonomies.ContentTaxonomy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_content_taxonomies");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_content_taxonomies_key");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_content_taxonomies_parent_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_content_taxonomies_tenant_id");

                    b.ToTable("content_taxonomies", (string)null);
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Workflows.ContentWorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_content_workflow_definitions");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_content_workflow_definitions_key");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_content_workflow_definitions_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_content_workflow_definitions_tenant_id");

                    b.ToTable("content_workflow_definitions", (string)null);
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Workflows.ContentWorkflowState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_final");

                    b.Property<bool>("IsInitial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_initial");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_content_workflow_states");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_content_workflow_states_tenant_id");

                    b.HasIndex("WorkflowDefinitionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_content_workflow_states_workflow_definition_id_key");

                    b.ToTable("content_workflow_states", (string)null);
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Workflows.ContentWorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("FromStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_state_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ToStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_state_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_content_workflow_transitions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_content_workflow_transitions_tenant_id");

                    b.HasIndex("ToStateId")
                        .HasDatabaseName("ix_content_workflow_transitions_to_state_id");

                    b.HasIndex("WorkflowDefinitionId")
                        .HasDatabaseName("ix_content_workflow_transitions_workflow_definition_id");

                    b.HasIndex("FromStateId", "ToStateId")
                        .IsUnique()
                        .HasDatabaseName("ix_content_workflow_transitions_from_state_id_to_state_id");

                    b.ToTable("content_workflow_transitions", (string)null);
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.ContentTypes.ContentFieldDefinition", b =>
                {
                    b.HasOne("NovaCore.Content.Domain.Entities.ContentTypes.ContentType", "ContentType")
                        .WithMany("FieldDefinitions")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_field_definitions_content_types_content_type_id");

                    b.Navigation("ContentType");
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.Content", b =>
                {
                    b.HasOne("NovaCore.Content.Domain.Entities.ContentTypes.ContentType", "ContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contents_content_types_content_type_id");

                    b.HasOne("NovaCore.Content.Domain.Entities.Contents.ContentVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_contents_content_versions_current_version_id");

                    b.HasOne("NovaCore.Content.Domain.Entities.Contents.ContentVersion", "PublishedVersion")
                        .WithMany()
                        .HasForeignKey("PublishedVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_contents_content_versions_published_version_id");

                    b.Navigation("ContentType");

                    b.Navigation("CurrentVersion");

                    b.Navigation("PublishedVersion");
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.ContentAudience", b =>
                {
                    b.HasOne("NovaCore.Content.Domain.Entities.Contents.Content", "Content")
                        .WithMany("Audiences")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_audiences_contents_content_id");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.ContentContributor", b =>
                {
                    b.HasOne("NovaCore.Content.Domain.Entities.Contents.Content", "Content")
                        .WithMany("Contributors")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_contributors_contents_content_id");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.ContentLocalization", b =>
                {
                    b.HasOne("NovaCore.Content.Domain.Entities.Contents.Content", "Content")
                        .WithMany("Localizations")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_localizations_contents_content_id");

                    b.HasOne("NovaCore.Content.Domain.Entities.Contents.ContentVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_localizations_content_versions_version_id");

                    b.Navigation("Content");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.ContentPublication", b =>
                {
                    b.HasOne("NovaCore.Content.Domain.Entities.Contents.Content", "Content")
                        .WithMany("Publications")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_publications_contents_content_id");

                    b.HasOne("NovaCore.Content.Domain.Entities.Contents.ContentVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_publications_content_versions_version_id");

                    b.Navigation("Content");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.ContentRelationship", b =>
                {
                    b.HasOne("NovaCore.Content.Domain.Entities.Contents.Content", "SourceContent")
                        .WithMany("Relationships")
                        .HasForeignKey("SourceContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_relationships_contents_source_content_id");

                    b.Navigation("SourceContent");
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.ContentTaxonomyAssignment", b =>
                {
                    b.HasOne("NovaCore.Content.Domain.Entities.Contents.Content", "Content")
                        .WithMany("TaxonomyAssignments")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_taxonomy_assignments_contents_content_id");

                    b.HasOne("NovaCore.Content.Domain.Entities.Taxonomies.ContentTaxonomy", "Taxonomy")
                        .WithMany()
                        .HasForeignKey("TaxonomyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_taxonomy_assignments_content_taxonomies_taxonomy_id");

                    b.Navigation("Content");

                    b.Navigation("Taxonomy");
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.ContentVersion", b =>
                {
                    b.HasOne("NovaCore.Content.Domain.Entities.Contents.Content", "Content")
                        .WithMany("Versions")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_versions_contents_content_id");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.ContentWorkflowInstance", b =>
                {
                    b.HasOne("NovaCore.Content.Domain.Entities.Contents.Content", "Content")
                        .WithMany("WorkflowInstances")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_workflow_instances_contents_content_id");

                    b.HasOne("NovaCore.Content.Domain.Entities.Workflows.ContentWorkflowDefinition", "WorkflowDefinition")
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_workflow_instances_content_workflow_definitions_wor");

                    b.Navigation("Content");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Taxonomies.ContentTaxonomy", b =>
                {
                    b.HasOne("NovaCore.Content.Domain.Entities.Taxonomies.ContentTaxonomy", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_content_taxonomies_content_taxonomies_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Workflows.ContentWorkflowState", b =>
                {
                    b.HasOne("NovaCore.Content.Domain.Entities.Workflows.ContentWorkflowDefinition", "WorkflowDefinition")
                        .WithMany("States")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_workflow_states_content_workflow_definitions_workfl");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Workflows.ContentWorkflowTransition", b =>
                {
                    b.HasOne("NovaCore.Content.Domain.Entities.Workflows.ContentWorkflowState", "FromState")
                        .WithMany("OutgoingTransitions")
                        .HasForeignKey("FromStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_workflow_transitions_content_workflow_states_from_s");

                    b.HasOne("NovaCore.Content.Domain.Entities.Workflows.ContentWorkflowState", "ToState")
                        .WithMany("IncomingTransitions")
                        .HasForeignKey("ToStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_workflow_transitions_content_workflow_states_to_sta");

                    b.HasOne("NovaCore.Content.Domain.Entities.Workflows.ContentWorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_workflow_transitions_content_workflow_definitions_w");

                    b.Navigation("FromState");

                    b.Navigation("ToState");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.ContentTypes.ContentType", b =>
                {
                    b.Navigation("FieldDefinitions");
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Contents.Content", b =>
                {
                    b.Navigation("Audiences");

                    b.Navigation("Contributors");

                    b.Navigation("Localizations");

                    b.Navigation("Publications");

                    b.Navigation("Relationships");

                    b.Navigation("TaxonomyAssignments");

                    b.Navigation("Versions");

                    b.Navigation("WorkflowInstances");
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Taxonomies.ContentTaxonomy", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Workflows.ContentWorkflowDefinition", b =>
                {
                    b.Navigation("States");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("NovaCore.Content.Domain.Entities.Workflows.ContentWorkflowState", b =>
                {
                    b.Navigation("IncomingTransitions");

                    b.Navigation("OutgoingTransitions");
                });
#pragma warning restore 612, 618
        }
    }
}
