<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../src/BuildingBlocks/BuildingBlock.Domain/BuildingBlock.Domain.csproj" />
    <ProjectReference Include="../../../../src/BuildingBlocks/BuildingBlock.Application/BuildingBlock.Application.csproj" />
  </ItemGroup>

</Project>
