<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\BuildingBlock.SharedKernel\BuildingBlock.SharedKernel.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\BuildingBlock.Observability\BuildingBlock.Observability.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\BuildingBlock.Infrastructure\BuildingBlock.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>NovaCore.YarpApiGateway</RootNamespace>
    <AssemblyName>NovaCore.YarpApiGateway</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Yarp.ReverseProxy" />
  </ItemGroup>

</Project>
