// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaCore.Order.Persistence.Engine;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NovaCore.Order.Persistence.Storage.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260806081927_AddOrderTags")]
    partial class AddOrderTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NovaCore.BuildingBlock.Persistence.Ef.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consumer_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headers_json");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_retry_at");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("idx_inbox_processed_at");

                    b.HasIndex("MessageId", "ConsumerName")
                        .IsUnique()
                        .HasDatabaseName("idx_inbox_message_consumer_unique");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_inbox_status_created_at");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("idx_inbox_status_next_retry_at");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("NovaCore.BuildingBlock.Persistence.Ef.Inbox.InboxRetryHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consumer_name");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Exception")
                        .HasColumnType("text")
                        .HasColumnName("exception");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Operator")
                        .HasColumnType("text")
                        .HasColumnName("operator");

                    b.Property<int>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result");

                    b.Property<int>("RetryNumber")
                        .HasColumnType("integer")
                        .HasColumnName("retry_number");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_inbox_retry_histories");

                    b.ToTable("inbox_retry_histories", (string)null);
                });

            modelBuilder.Entity("NovaCore.BuildingBlock.Persistence.Ef.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("system")
                        .HasColumnName("actor_type");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_outbox_unprocessed_created_at")
                        .HasFilter("\"processed_at\" IS NULL");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("idx_outbox_processed_at");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Catalogs.ProductCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("VariationId")
                        .HasColumnType("uuid")
                        .HasColumnName("variation_id");

                    b.Property<string>("VariationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("variation_name");

                    b.HasKey("Id")
                        .HasName("pk_product_catalogs");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_product_catalogs_tenant_id");

                    b.HasIndex("ProductId", "VariationId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_catalogs_product_id_variation_id");

                    b.ToTable("product_catalogs", (string)null);
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("order_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_orders_created_at");

                    b.HasIndex("IdempotencyKey")
                        .HasDatabaseName("ix_orders_idempotency_key");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_orders_tenant_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_orders_status_created_at");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.OrderDiscount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AppliedAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("applied_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<long?>("OrderItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_item_id");

                    b.Property<Guid?>("OrderShippingId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_shipping_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_code");

                    b.Property<string>("SourceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_id");

                    b.Property<int>("Target")
                        .HasColumnType("integer")
                        .HasColumnName("target");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_order_discounts");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_discounts_order_id");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("ix_order_discounts_order_item_id");

                    b.HasIndex("OrderShippingId")
                        .HasDatabaseName("ix_order_discounts_order_shipping_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_order_discounts_tenant_id");

                    b.ToTable("order_discounts", (string)null);
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BundleDiscount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("bundle_discount");

                    b.Property<decimal>("CouponDiscount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("coupon_discount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("final_amount");

                    b.Property<decimal>("GiftDiscount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gift_discount");

                    b.Property<decimal>("ManualDiscount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("manual_discount");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("OrderItemNo")
                        .HasColumnType("integer")
                        .HasColumnName("order_item_no");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<decimal>("ProductPromotionDiscount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("product_promotion_discount");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("VariationId")
                        .HasColumnType("uuid")
                        .HasColumnName("variation_id");

                    b.Property<string>("VariationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("variation_name");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_order_items_tenant_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.OrderOwner", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner_email");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner_name");

                    b.Property<string>("OwnerPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("owner_phone");

                    b.Property<string>("OwnerPhoneReverse")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("owner_phone_reverse");

                    b.Property<string>("OwnerPhoneSearch")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("owner_phone_search");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("OrderId")
                        .HasName("pk_order_owners");

                    b.HasIndex("IdempotencyKey")
                        .HasDatabaseName("ix_order_owners_idempotency_key");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_order_owners_owner_id");

                    b.HasIndex("OwnerName")
                        .HasDatabaseName("ix_order_owners_owner_name");

                    b.HasIndex("OwnerPhoneReverse")
                        .HasDatabaseName("ix_order_owners_owner_phone_reverse");

                    b.HasIndex("OwnerPhoneSearch")
                        .HasDatabaseName("ix_order_owners_owner_phone_search");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_order_owners_tenant_id");

                    b.HasIndex("OwnerId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_order_owners_owner_id_idempotency_key")
                        .HasFilter("\"idempotency_key\" IS NOT NULL");

                    b.ToTable("order_owners", (string)null);
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.OrderPrice", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<decimal>("CouponDiscount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("coupon_discount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("exchange_rate");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("grand_total");

                    b.Property<decimal>("ItemDiscount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("item_discount");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("platform_fee");

                    b.Property<decimal>("PromotionDiscount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("promotion_discount");

                    b.Property<decimal>("RoundingAdjustment")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("rounding_adjustment");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("service_fee");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("OrderId")
                        .HasName("pk_order_prices");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_order_prices_tenant_id");

                    b.ToTable("order_prices", (string)null);
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.OrderShipping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("ArrivedAtWarehouseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrived_at_warehouse_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("FinalFee")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("final_fee");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTime?>("InTransitAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("in_transit_at");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<decimal>("OriginalFee")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("original_fee");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("receiver_name");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("receiver_phone");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shipped_at");

                    b.Property<int>("ShippingMethod")
                        .HasColumnType("integer")
                        .HasColumnName("shipping_method");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_order_shippings");

                    b.HasIndex("IdempotencyKey")
                        .HasDatabaseName("ix_order_shippings_idempotency_key");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_order_shippings_order_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_order_shippings_tenant_id");

                    b.ToTable("order_shippings", (string)null);
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.OrderStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("changed_by_name");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("CurrentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("current_status");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("integer")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_order_status_histories");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_order_status_histories_tenant_id");

                    b.HasIndex("OrderId", "ChangedAt")
                        .HasDatabaseName("ix_order_status_histories_order_id_changed_at");

                    b.ToTable("order_status_histories", (string)null);
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.OrderTag", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("OrderId", "TagId")
                        .HasName("pk_order_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_order_tags_tag_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_order_tags_tenant_id");

                    b.ToTable("order_tags", (string)null);
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.OrderTax", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tax_name");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("tax_rate");

                    b.Property<int>("TaxType")
                        .HasColumnType("integer")
                        .HasColumnName("tax_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_order_taxes");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_taxes_order_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_order_taxes_tenant_id");

                    b.ToTable("order_taxes", (string)null);
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Tags.OrderTagDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_order_tag_definitions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_order_tag_definitions_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_order_tag_definitions_is_active");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_order_tag_definitions_tenant_id");

                    b.ToTable("order_tag_definitions", (string)null);
                });

            modelBuilder.Entity("NovaCore.Order.Persistence.Reliability.Saga.SagaExecutionRecordEntity", b =>
                {
                    b.Property<string>("SagaId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("saga_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletedStepsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("completed_steps_json");

                    b.Property<string>("ContextDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("context_data_json");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("SagaName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("saga_name");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.HasKey("SagaId")
                        .HasName("pk_saga_execution_records");

                    b.HasIndex("SagaName", "StartedAt")
                        .HasDatabaseName("ix_saga_execution_records_saga_name_started_at");

                    b.HasIndex("State", "StartedAt")
                        .HasDatabaseName("ix_saga_execution_records_state_started_at");

                    b.ToTable("saga_execution_records", (string)null);
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.OrderDiscount", b =>
                {
                    b.HasOne("NovaCore.Order.Domain.Entities.Orders.Order", null)
                        .WithMany("Discounts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_discounts_orders_order_id");

                    b.HasOne("NovaCore.Order.Domain.Entities.Orders.OrderItem", null)
                        .WithMany("Discounts")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_order_discounts_order_items_order_item_id");

                    b.HasOne("NovaCore.Order.Domain.Entities.Orders.OrderShipping", null)
                        .WithMany()
                        .HasForeignKey("OrderShippingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_order_discounts_order_shipping_order_shipping_id");

                    b.OwnsOne("NovaCore.Order.Domain.ValueObjects.DiscountRule", "Rule", b1 =>
                        {
                            b1.Property<long>("OrderDiscountId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<decimal?>("MaximumDiscount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("rule_maximum_discount");

                            b1.Property<int>("Method")
                                .HasColumnType("integer")
                                .HasColumnName("rule_method");

                            b1.Property<decimal?>("MinimumSpend")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("rule_minimum_spend");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("rule_value");

                            b1.HasKey("OrderDiscountId");

                            b1.ToTable("order_discounts");

                            b1.WithOwner()
                                .HasForeignKey("OrderDiscountId")
                                .HasConstraintName("fk_order_discounts_order_discounts_id");
                        });

                    b.Navigation("Rule")
                        .IsRequired();
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.OrderItem", b =>
                {
                    b.HasOne("NovaCore.Order.Domain.Entities.Orders.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.OrderOwner", b =>
                {
                    b.HasOne("NovaCore.Order.Domain.Entities.Orders.Order", null)
                        .WithOne("Owner")
                        .HasForeignKey("NovaCore.Order.Domain.Entities.Orders.OrderOwner", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_owners_orders_order_id");
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.OrderPrice", b =>
                {
                    b.HasOne("NovaCore.Order.Domain.Entities.Orders.Order", null)
                        .WithOne("Price")
                        .HasForeignKey("NovaCore.Order.Domain.Entities.Orders.OrderPrice", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_prices_orders_order_id");
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.OrderShipping", b =>
                {
                    b.HasOne("NovaCore.Order.Domain.Entities.Orders.Order", null)
                        .WithOne("Shipping")
                        .HasForeignKey("NovaCore.Order.Domain.Entities.Orders.OrderShipping", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_shippings_orders_order_id");
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.OrderStatusHistory", b =>
                {
                    b.HasOne("NovaCore.Order.Domain.Entities.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_status_histories_orders_order_id");
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.OrderTag", b =>
                {
                    b.HasOne("NovaCore.Order.Domain.Entities.Orders.Order", null)
                        .WithMany("Tags")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_tags_orders_order_id");

                    b.HasOne("NovaCore.Order.Domain.Entities.Tags.OrderTagDefinition", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_tags_order_tag_definitions_tag_id");
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.OrderTax", b =>
                {
                    b.HasOne("NovaCore.Order.Domain.Entities.Orders.Order", null)
                        .WithMany("Taxes")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_taxes_orders_order_id");
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.Order", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Items");

                    b.Navigation("Owner")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Shipping")
                        .IsRequired();

                    b.Navigation("Tags");

                    b.Navigation("Taxes");
                });

            modelBuilder.Entity("NovaCore.Order.Domain.Entities.Orders.OrderItem", b =>
                {
                    b.Navigation("Discounts");
                });
#pragma warning restore 612, 618
        }
    }
}
