// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaCore.Inventory.Persistence.Engine;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NovaCore.Inventory.Persistence.Storage.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260806050622_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NovaCore.BuildingBlock.Persistence.Ef.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consumer_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headers_json");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_retry_at");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("idx_inbox_processed_at");

                    b.HasIndex("MessageId", "ConsumerName")
                        .IsUnique()
                        .HasDatabaseName("idx_inbox_message_consumer_unique");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_inbox_status_created_at");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("idx_inbox_status_next_retry_at");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("NovaCore.BuildingBlock.Persistence.Ef.Inbox.InboxRetryHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consumer_name");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Exception")
                        .HasColumnType("text")
                        .HasColumnName("exception");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Operator")
                        .HasColumnType("text")
                        .HasColumnName("operator");

                    b.Property<int>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result");

                    b.Property<int>("RetryNumber")
                        .HasColumnType("integer")
                        .HasColumnName("retry_number");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_inbox_retry_histories");

                    b.ToTable("inbox_retry_histories", (string)null);
                });

            modelBuilder.Entity("NovaCore.BuildingBlock.Persistence.Ef.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("system")
                        .HasColumnName("actor_type");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_outbox_unprocessed_created_at")
                        .HasFilter("\"processed_at\" IS NULL");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("idx_outbox_processed_at");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.Inventories.InventoryStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DamagedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("damaged_quantity");

                    b.Property<int>("IncomingQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("incoming_quantity");

                    b.Property<int>("MaximumStock")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_stock");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int>("OnHandQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("on_hand_quantity");

                    b.Property<int>("OutgoingQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("outgoing_quantity");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("ReorderPoint")
                        .HasColumnType("integer")
                        .HasColumnName("reorder_point");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_quantity");

                    b.Property<int>("SafetyStock")
                        .HasColumnType("integer")
                        .HasColumnName("safety_stock");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_inventory_stocks");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_inventory_stocks_product_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_inventory_stocks_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_inventory_stocks_tenant_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_inventory_stocks_warehouse_id");

                    b.HasIndex("VariantId", "WarehouseId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_stocks_variant_id_warehouse_id");

                    b.ToTable("inventory_stocks", (string)null);
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventoryCounts.InventoryCount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CountDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("count_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_inventory_counts");

                    b.HasIndex("CountDate")
                        .HasDatabaseName("ix_inventory_counts_count_date");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_counts_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_inventory_counts_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_inventory_counts_tenant_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_inventory_counts_warehouse_id");

                    b.ToTable("inventory_counts", (string)null);
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventoryCounts.InventoryCountItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ActualQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("actual_quantity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DifferenceQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("difference_quantity");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("expected_quantity");

                    b.Property<Guid>("InventoryCountId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_count_id");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<string>("Note")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("")
                        .HasColumnName("note");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_count_items");

                    b.HasIndex("InventoryCountId")
                        .HasDatabaseName("ix_inventory_count_items_inventory_count_id");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("ix_inventory_count_items_inventory_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_inventory_count_items_tenant_id");

                    b.ToTable("inventory_count_items", (string)null);
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventoryDocuments.InventoryDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<Guid?>("DestinationWarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_warehouse_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number");

                    b.Property<short>("Reason")
                        .HasColumnType("smallint")
                        .HasColumnName("reason");

                    b.Property<Guid?>("SourceWarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_warehouse_id");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_inventory_documents");

                    b.HasIndex("DestinationWarehouseId")
                        .HasDatabaseName("ix_inventory_documents_destination_warehouse_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_documents_number");

                    b.HasIndex("SourceWarehouseId")
                        .HasDatabaseName("ix_inventory_documents_source_warehouse_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_inventory_documents_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_inventory_documents_tenant_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_inventory_documents_type");

                    b.ToTable("inventory_documents", (string)null);
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventoryDocuments.InventoryDocumentItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<Guid>("InventoryDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_document_id");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<Guid?>("InventoryLotId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_lot_id");

                    b.Property<Guid?>("InventorySerialId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_serial_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit_of_measure");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_document_items");

                    b.HasIndex("InventoryDocumentId")
                        .HasDatabaseName("ix_inventory_document_items_inventory_document_id");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("ix_inventory_document_items_inventory_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_inventory_document_items_tenant_id");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("ix_inventory_document_items_variant_id");

                    b.ToTable("inventory_document_items", (string)null);
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventoryLots.InventoryLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryOfOrigin")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("country_of_origin");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_date");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_number");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("manufacture_date");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<string>("SupplierLotNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("supplier_lot_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_inventory_lots");

                    b.HasIndex("ExpiredDate")
                        .HasDatabaseName("ix_inventory_lots_expired_date");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("ix_inventory_lots_inventory_id");

                    b.HasIndex("LotNumber")
                        .HasDatabaseName("ix_inventory_lots_lot_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_inventory_lots_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_inventory_lots_tenant_id");

                    b.ToTable("inventory_lots", (string)null);
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventoryReservations.InventoryReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<string>("ExternalReference")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("")
                        .HasColumnName("external_reference");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("number");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<short?>("ReferenceType")
                        .HasColumnType("smallint")
                        .HasColumnName("reference_type");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_inventory_reservations");

                    b.HasIndex("ExpiredAt")
                        .HasDatabaseName("ix_inventory_reservations_expired_at");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("ix_inventory_reservations_inventory_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_reservations_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_inventory_reservations_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_inventory_reservations_tenant_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_inventory_reservations_warehouse_id");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("ix_inventory_reservations_reference_type_reference_id");

                    b.ToTable("inventory_reservations", (string)null);
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventorySerials.InventorySerial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("InventoryDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_document_id");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<Guid?>("InventoryReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_reservation_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_inventory_serials");

                    b.HasIndex("InventoryDocumentId")
                        .HasDatabaseName("ix_inventory_serials_inventory_document_id");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("ix_inventory_serials_inventory_id");

                    b.HasIndex("InventoryReservationId")
                        .HasDatabaseName("ix_inventory_serials_inventory_reservation_id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_serials_serial_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_inventory_serials_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_inventory_serials_tenant_id");

                    b.ToTable("inventory_serials", (string)null);
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventoryTransactions.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AfterOnHandQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("after_on_hand_quantity");

                    b.Property<int>("AfterReservedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("after_reserved_quantity");

                    b.Property<int>("BeforeOnHandQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("before_on_hand_quantity");

                    b.Property<int>("BeforeReservedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("before_reserved_quantity");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<Guid?>("InventoryDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_document_id");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<Guid?>("InventoryReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_reservation_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_transactions");

                    b.HasIndex("InventoryDocumentId")
                        .HasDatabaseName("ix_inventory_transactions_inventory_document_id");

                    b.HasIndex("InventoryReservationId")
                        .HasDatabaseName("ix_inventory_transactions_inventory_reservation_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_inventory_transactions_product_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_inventory_transactions_tenant_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_inventory_transactions_type");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_inventory_transactions_warehouse_id");

                    b.HasIndex("InventoryId", "CreatedAt")
                        .HasDatabaseName("ix_inventory_transactions_inventory_id_created_at");

                    b.ToTable("inventory_transactions", (string)null);
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.Warehouses.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowNegativeStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_negative_stock");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<bool>("SupportsPicking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("supports_picking");

                    b.Property<bool>("SupportsReceiving")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("supports_receiving");

                    b.Property<bool>("SupportsReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("supports_reservation");

                    b.Property<bool>("SupportsReturns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("supports_returns");

                    b.Property<bool>("SupportsShipping")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("supports_shipping");

                    b.Property<bool>("SupportsTransfer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("supports_transfer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("UTC")
                        .HasColumnName("time_zone");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_warehouses_code");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_warehouses_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_warehouses_tenant_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_warehouses_type");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.Warehouses.WarehouseZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowMixedLot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_mixed_lot");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<short>("PickingStrategy")
                        .HasColumnType("smallint")
                        .HasColumnName("picking_strategy");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_warehouse_zones");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_warehouse_zones_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_warehouse_zones_tenant_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_warehouse_zones_type");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_warehouse_zones_warehouse_id_code");

                    b.ToTable("warehouse_zones", (string)null);
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.Inventories.InventoryStock", b =>
                {
                    b.HasOne("NovaCore.Inventory.Domain.Entities.Warehouses.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_stocks_warehouses_warehouse_id");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventoryCounts.InventoryCount", b =>
                {
                    b.HasOne("NovaCore.Inventory.Domain.Entities.Warehouses.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_counts_warehouses_warehouse_id");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventoryCounts.InventoryCountItem", b =>
                {
                    b.HasOne("NovaCore.Inventory.Domain.Entities.InventoryCounts.InventoryCount", "InventoryCount")
                        .WithMany("Items")
                        .HasForeignKey("InventoryCountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_count_items_inventory_counts_inventory_count_id");

                    b.HasOne("NovaCore.Inventory.Domain.Entities.Inventories.InventoryStock", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_count_items_inventory_stocks_inventory_id");

                    b.Navigation("Inventory");

                    b.Navigation("InventoryCount");
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventoryDocuments.InventoryDocument", b =>
                {
                    b.HasOne("NovaCore.Inventory.Domain.Entities.Warehouses.Warehouse", "DestinationWarehouse")
                        .WithMany()
                        .HasForeignKey("DestinationWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_documents_warehouses_destination_warehouse_id");

                    b.HasOne("NovaCore.Inventory.Domain.Entities.Warehouses.Warehouse", "SourceWarehouse")
                        .WithMany()
                        .HasForeignKey("SourceWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_documents_warehouses_source_warehouse_id");

                    b.Navigation("DestinationWarehouse");

                    b.Navigation("SourceWarehouse");
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventoryDocuments.InventoryDocumentItem", b =>
                {
                    b.HasOne("NovaCore.Inventory.Domain.Entities.InventoryDocuments.InventoryDocument", "Document")
                        .WithMany("Items")
                        .HasForeignKey("InventoryDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_document_items_inventory_documents_inventory_docu");

                    b.HasOne("NovaCore.Inventory.Domain.Entities.Inventories.InventoryStock", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_document_items_inventory_stocks_inventory_id");

                    b.Navigation("Document");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventoryLots.InventoryLot", b =>
                {
                    b.HasOne("NovaCore.Inventory.Domain.Entities.Inventories.InventoryStock", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_lots_inventory_stocks_inventory_id");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventoryReservations.InventoryReservation", b =>
                {
                    b.HasOne("NovaCore.Inventory.Domain.Entities.Inventories.InventoryStock", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_reservations_inventory_stocks_inventory_id");

                    b.HasOne("NovaCore.Inventory.Domain.Entities.Warehouses.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_reservations_warehouses_warehouse_id");

                    b.Navigation("Inventory");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventorySerials.InventorySerial", b =>
                {
                    b.HasOne("NovaCore.Inventory.Domain.Entities.InventoryDocuments.InventoryDocument", "Document")
                        .WithMany()
                        .HasForeignKey("InventoryDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_serials_inventory_documents_inventory_document_id");

                    b.HasOne("NovaCore.Inventory.Domain.Entities.Inventories.InventoryStock", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_serials_inventory_stocks_inventory_id");

                    b.HasOne("NovaCore.Inventory.Domain.Entities.InventoryReservations.InventoryReservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("InventoryReservationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inventory_serials_inventory_reservations_inventory_reservat");

                    b.Navigation("Document");

                    b.Navigation("Inventory");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventoryTransactions.InventoryTransaction", b =>
                {
                    b.HasOne("NovaCore.Inventory.Domain.Entities.InventoryDocuments.InventoryDocument", "Document")
                        .WithMany()
                        .HasForeignKey("InventoryDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_transactions_inventory_documents_inventory_docume");

                    b.HasOne("NovaCore.Inventory.Domain.Entities.Inventories.InventoryStock", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_transactions_inventory_stocks_inventory_id");

                    b.HasOne("NovaCore.Inventory.Domain.Entities.InventoryReservations.InventoryReservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("InventoryReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_transactions_inventory_reservations_inventory_res");

                    b.HasOne("NovaCore.Inventory.Domain.Entities.Warehouses.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_transactions_warehouses_warehouse_id");

                    b.Navigation("Document");

                    b.Navigation("Inventory");

                    b.Navigation("Reservation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.Warehouses.WarehouseZone", b =>
                {
                    b.HasOne("NovaCore.Inventory.Domain.Entities.Warehouses.Warehouse", "Warehouse")
                        .WithMany("Zones")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_warehouse_zones_warehouses_warehouse_id");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventoryCounts.InventoryCount", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.InventoryDocuments.InventoryDocument", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("NovaCore.Inventory.Domain.Entities.Warehouses.Warehouse", b =>
                {
                    b.Navigation("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
